import { PATTERN_TYPE } from '../renderer/domains/Awakening/awakeningUtil';

export default {
  awakenPatterns: [
    {
      id: 1,
      uid: 'AUTO_PAROLI-1',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 2,
      uid: 'AUTO_PAROLI-2',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 3,
      uid: 'AUTO_PAROLI-3',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 4,
      uid: 'AUTO_PAROLI-4',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 5,
      uid: 'AUTO_PAROLI-5',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 6,
      uid: 'AUTO_PAROLI-6',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 7,
      uid: 'AUTO_PAROLI-7',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 8,
      uid: 'AUTO_PAROLI-8',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 9,
      uid: 'AUTO_PAROLI-9',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 10,
      uid: 'AUTO_PAROLI-10',
      type: PATTERN_TYPE.AUTO_PAROLI,
      condition: 'T',
      betLoop: [10],
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 1.95 },
        { betType: true, betAmount: 3.8 },
        { betType: true, betAmount: 7.41 },
        { betType: true, betAmount: 14.46 },
        { betType: true, betAmount: 28.2 },
      ],
    },
    {
      id: 11,
      uid: 'MINI_AWAKEN-1',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'T',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: false, betAmount: 2 },
        { betType: true, betAmount: 5 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 1,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 12,
      uid: 'MINI_AWAKEN-2',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'T',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: false, betAmount: 2 },
        { betType: true, betAmount: 5 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 2,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 13,
      uid: 'MINI_AWAKEN-3',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'T',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: true, betAmount: 2 },
        { betType: false, betAmount: 5 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 3,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 14,
      uid: 'MINI_AWAKEN-4',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: false, betAmount: 2.5 },
        { betType: false, betAmount: 7 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 1,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 15,
      uid: 'MINI_AWAKEN-5',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'T',
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: false, betAmount: 2.5 },
        { betType: false, betAmount: 7 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 2,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 16,
      uid: 'MINI_AWAKEN-6',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: true, betAmount: 2.5 },
        { betType: true, betAmount: 7 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 3,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 17,
      uid: 'MINI_AWAKEN-7',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: false, betAmount: 3 },
        { betType: true, betAmount: 9 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 1,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 18,
      uid: 'MINI_AWAKEN-8',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 3 },
        { betType: false, betAmount: 9 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 2,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 19,
      uid: 'MINI_AWAKEN-9',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'T',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: false, betAmount: 3 },
        { betType: false, betAmount: 9 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 3,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 20,
      uid: 'MINI_AWAKEN-10',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: true, betAmount: 2.5 },
        { betType: true, betAmount: 7.5 },
        { betType: false, betAmount: 18 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 1,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 21,
      uid: 'MINI_AWAKEN-11',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: false, betAmount: 2.5 },
        { betType: true, betAmount: 7.5 },
        { betType: true, betAmount: 18 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 2,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 22,
      uid: 'MINI_AWAKEN-12',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: false, betAmount: 3 },
        { betType: false, betAmount: 9 },
        { betType: true, betAmount: 27 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 1,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 23,
      uid: 'MINI_AWAKEN-13',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'T',
      betOrders: [
        { betType: true, betAmount: 1 },
        { betType: true, betAmount: 3 },
        { betType: true, betAmount: 9 },
        { betType: true, betAmount: 27 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 2,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
    {
      id: 24,
      uid: 'MINI_AWAKEN-14',
      type: 'MINI_AWAKEN',
      isActive: false,
      condition: 'G',
      betOrders: [
        { betType: false, betAmount: 1 },
        { betType: true, betAmount: 3 },
        { betType: true, betAmount: 9 },
        { betType: false, betAmount: 27 },
      ],
      betLoop: [0],
      betRatioInit: [1],
      recentProfit: 0,
      recentBetAmount: 0,
      realWinCount: 0,
      maxWinCount: 3,
      virtualProfit: 0,
      martingaleWinLoop: [],
      martingaleWinLoopPos: 0,
      miniAwakenLoseList: [1],
      miniAwakenLosePos: 0,
      miniAwakenWinCount: 0,
      miniAwakenLoseCount: 0,
    },
  ],
};
